### PR TITLE
Added css to move table of content to right

### LINKED ISSUE #105: Add Content Navigation Bar in Right Side of Documentation pages
The current documentation layout has no side navigation bar, and looks something like this:
Screenshot from 2020-10-05 23-41-37

As the content on the upcoming pages is increasing, navigation to each section is becoming harder. To deal with such a bulkier page, I could break the content into multiple pages, but that would reduce the charm as the user would be just navigating between pages(due to references). Hence, I propose to have a content navigation bar on the right side, utilising the vacant space, helping the reader to have a better experience.

### PR DESCRIPTION
**Pull request by Signior-X**
Fixes #105 
So so the Table of content written, we can enclose it in a div tag with markdown="1" and id="table-of-content"
The rest of css plays the role, and as @PIYUSHgoyal16 you wanted, it remains on the screen even on scroll.

I have added @ media rule, so that this only applies for large screen width devices, where there is space to move it to the right.

Currently I have added the div in only one documentation, check if this feels good, I will add it to more of the pages.

### CODE REVIEW

**Comment by PIYUSHgoyal16** [comment]
Thanks, @Signior-X this really seems nice \o/ However, there are a couple of issues that are needed to be fixed:

1) Separate Scrollbar for the content section
Currently, there is no scrollbar in the content section, meaning if the table increases beyond a length the user would not be able to navigate in the bottom part of the section :-/
Kindly add a separate scrollbar in the right-hand side as well.

2) Self-Adjustable Top Margin of Content Table (Optional)
Currently, the content table is exactly static, it leaves a space on the top that doesn't look appealing.
Screenshot from 2020-10-06 18-01-07
Kindly make the top margin self-adjustable.

**Comment by Signior-X** [comment]
Okay I will make the necessary changes and let you know.

**Comment by Signior-X** [comment]
@PIYUSHgoyal16 
Instead I have done as you suggested, this time one can use the Automatic Table of creation help provided by the minimal mistakes. So that can be used, I have also added a custom h range creation for table of creation, so if the table is getting very long, you can adjust the h range.
Also, now no need to enclose and create a custom Table of content on the page.

Check this and tell if further changes are needed.

**Comment by Signior-X** [comment]
I guess the already manually created Table of content can be removed now... what say?

**Comment by PIYUSHgoyal16** [comment]
Excellent @Signior-X 
Sure, you can remove the manually entered Table of Contents. Thanks, @dheeraj135 `toc` was really a nice idea :-) 

@tillkamppeter kindly review and merge the changes.

**Comment by Signior-X** [comment]
Now all set successfully rebased and removed old table of contents.
@PIYUSHgoyal16 check finally if changes are okay or not.

**Comment by PIYUSHgoyal16** [comment]
@tillkamppeter kindly merge the changes.

**Review by tillkamppeter — APPROVED** [review]

**Comment by tillkamppeter** [comment]
@Signior-X, thank you for your contribution. I have it merged now.

**Pull request merged**
