### PR TITLE
Add comment provider to the website.

### PR DESCRIPTION
**Pull request by dheeraj135**
@tillkamppeter @sahilarora535 We need to change the plan of ```openprintingorg```. For testing purposes, I have added my Disqus account.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
To exactly what do I have to change my Disqus plan?

**Comment by dheeraj135** [comment]
As you can see in below screenshot, we need to change to Free subscription of the **Plus** plan.
screenshot from 2019-02-27 17-57-12

**Comment by dheeraj135** [comment]
@tillkamppeter ```openprintingorg``` is not serving ads now. I have updated the shortname.

**Comment by dheeraj135** [comment]
I am sorry for giving the wrong information. ```openprintingorg``` is **serving** ads. I didn't realize I had adblocker on.

**Comment by sahilarora535** [comment]
@dheeraj135 is this PR ready to be merged?

**Comment by dheeraj135** [comment]
No, it is not.

**Comment by dheeraj135** [comment]
@tillkamppeter Please merge this pull request.

**Comment by tillkamppeter** [comment]
It is working now. Thank you very much!

**Pull request merged**
