### PR TITLE
Add content on download and contact us page

### LINKED ISSUE #33: Add content to the 'Contact Us' Page
Add content to the `Contact Us` page which would be located here: https://openprinting.github.io/contact/

Depends on: #32

### LINKED ISSUE #37: Add content to the 'Downloads' page
Add content to the `Downloads` page located here: https://openprinting.github.io/downloads/
Depends on: #36

### PR DESCRIPTION
**Pull request by Sharadd15**
screenshot from 2019-02-20 21-30-14
screenshot from 2019-02-21 17-30-03
Closes #37 
Closes #33 
@tillkamppeter do we need any other changes ?

### CODE REVIEW

**Comment by dheeraj135** [comment]
@Sharadd15 Please squash your commits.

**Comment by Sharadd15** [comment]
hi @dheeraj135 
i kept them because if there is some other change that is to be made then i will have the images.  I have removed them anyways but still there are images which are not in use which were already there.

**Comment by sahilarora535** [comment]
@Sharadd15 your branch has conflicts. It would be great if you could rebase your branch and push the request again. Thank you.

**Comment by Sharadd15** [comment]
@sahilarora535 I have made the changes 
Thank you

**Pull request merged**
