### PR TITLE
Add collection for Driverless Printing

### LINKED ISSUE #38: Add a collection for 'Driverless Printing'
`Driverless Printing` should be made as a collection and a page should be made with the link embedded in the title bar as there is now: 
image

### PR DESCRIPTION
**Pull request by Sharadd15**
screenshot from 2019-03-04 20-41-45
screenshot from 2019-03-04 20-41-58
screenshot from 2019-03-04 20-42-02
screenshot from 2019-03-04 20-42-07
screenshot from 2019-03-04 20-42-13
Closes #38

### CODE REVIEW

**Comment by tillkamppeter** [comment]
I would like to ask you for a little change:
When presenting the 4 driverless IPP standards do not explain the PDLs in the first standard where they get mentioned, but explain them separately, after the standards, as I did in issue #38. This is less confusing as many of the PDLs are shared between various standards.

**Comment by Sharadd15** [comment]
screenshot from 2019-03-05 17-57-58
screenshot from 2019-03-05 17-58-02
@tillkamppeter I have made the changes . Do we need any other changes ?

**Comment by tillkamppeter** [comment]
In the paragraph about Apple Raster remove the last sentence ("This opens up ...") as all formats eliminate the need of printer drivers. In addition, we want to eliminate the need of any printer driver, not only non-free, so that the user gets the convenience of the printer just work, independent if it is newer or older than the client OS version.

**Comment by tillkamppeter** [comment]
Please replace "PWG raster trhe raster format ..." by "PWG Raster, a raster format, ...".

**Comment by Sharadd15** [comment]
screenshot from 2019-03-05 20-52-49
@tillkamppeter do we need other changes ?

**Comment by tillkamppeter** [comment]
OK. Great. Now it is all correct. Thank you.

**Pull request merged**
