### PR TITLE
Add Content to Download Page and Contact Us page

### LINKED ISSUE #33: Add content to the 'Contact Us' Page
Add content to the `Contact Us` page which would be located here: https://openprinting.github.io/contact/

Depends on: #32

### LINKED ISSUE #37: Add content to the 'Downloads' page
Add content to the `Downloads` page located here: https://openprinting.github.io/downloads/
Depends on: #36

### PR DESCRIPTION
**Pull request by Sharadd15**
Closes #37 
Closes #33 
rsz_screenshot_from_2019-02-19_17-49-53

rsz_screenshot_from_2019-02-19_17-32-03
rsz_screenshot_from_2019-02-19_17-32-13

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Looks all nice, but:
- Of the mailing lists only printing-architecture is still used. All the others are dead.
- The download page does not need to detail every file/directory in the download directory. Only make one icon for each active OpenPrinting project (like cups-filters, foomatic, ...) and one "Files" icon to browse the download area for accessing everything.

**Comment by Sharadd15** [comment]
screenshot from 2019-02-20 21-30-14

**Comment by Sharadd15** [comment]
I have removed the non working mailing list.
 @tillkamppeter can you please list the links that we want to have on download page from this [list](http://www.openprinting.org/download/l) or there a
screenshot from 2019-02-20 21-30-14
re other files that we want to link

**Comment by tillkamppeter** [comment]
@Sharadd15, your link to the list of downloadable items is broken. Can you correct it?

**Comment by Sharadd15** [comment]
@tillkamppeter here is the [link]http://www.openprinting.org/download/) I have also changed it in my original comment

**Comment by tillkamppeter** [comment]
Add direct links icons only for cups-filters, foomatic, ijs, and PPD. Let a "Files" icon point to http://www.openprinting.org/download/

**Pull request closed without merging**
